# coding=utf-8
from __future__ import absolute_import, division, print_function, \
  unicode_literals

from unittest import TestCase

from iota.crypto.signing import KeyGenerator, SigningKey


# noinspection SpellCheckingInspection
class KeyGeneratorTestCase(TestCase):
  def test_generate_single_key(self):
    """
    Generating a single key.
    """
    ag = KeyGenerator(
      seed = b'ITJVZTRFNBTRBSDIHWKOWCFBOQYQTENWLRUVHIBCBRTXYGDCCLLMM9DI9OQO',
    )

    self.assertListEqual(
      ag.get_keys(0),

      [
        SigningKey(
          b'JFIBLUBLSESJFHGXQIXDLAQDWYVASWQIUNKDIWKTLRXXPICK9FLYDGGNFFVVCPMXQJ'
          b'9GRHMZGEPXFJZITGJMSWBESYGGHLZCDUECMRZWD9AZTFCDYREMWZBQNROIHFANCCKT'
          b'YCYNUBTDBZZ9FJXABLDK9RDMQTDGDXKDXIVVQWKL9AX9UONTPMHFMNNLNRRWIVZQWC'
          b'N9YQMLOOCBWCPODBTLLAZKMVAGTUNVDQXNAMGOTNEYPBWHQEJGMJAGTPUFK9WHVJBC'
          b'UWZNFACTAWRRUTJPCEMRDMUJBJUWOHSWNXRECJDZFSDHLCNGHKQC9SBVCLX9XYDXBL'
          b'LGHWLYVMHUCKMGONXOAPZHFEPKDOFGVPUVJHZ9MKARJOBFHM9XYDZXDVPMMHRFOAO9'
          b'HTFLYM9OXWOHOFDLVYVHFJMMBWHIMUZDTJ9HHPXDCCPZCSDJQG9FXTNSGJFRJFXDUF'
          b'BRMCKHNWMHMGEGIGPRXIWLLAIBOWRJWDXN9SNDHYUUZUEA9KFFGLIUOD9ISSZF99AW'
          b'SMPDGAIUO9IKWYTHPOHT9IZVJRP9KUSPLKJTQVLOKYUI9ZJWSYRNDKCISDPGCKC9OB'
          b'ZJQRQWSUGEJQOJCMFPQT9VPBGIYTOILO9NDEPBUMMMUNCSDXAKRNDITYHZEABXFJXN'
          b'AWDFFRQMECVUFNWAUDBAMKWGHYQQQVOPAUMGZYQEMZPIDALOYSFPRGRDAIXQXTBVKH'
          b'XL9XKSZEUULZNYYNBESJJPC9UZAQAAMIYBSRP9DSCUCWUUNABNOXPVNUKLOBAYYTAF'
          b'ZILWBYPCOMACRQV9CAZMWSRNSTYFHWPQNPRPBPSSNOCIUQDUBDKQRACBIWFBDSL9ZK'
          b'OLFWA9VD9QWLZCDBR9WTKOROWNNKXMMLYULBFPBHIJRBRAJ9KTHOLTURRYSCMOKYEJ'
          b'VVXNLXFDQVVTDBITCWAHANCEZMWOARWCIDIHYXBTCKFNBJDSOMTK9ZWYHLRHXTRYHV'
          b'AOJFKUQODOXWOJBDRFSZIEOOOARIZWHHFMWIBO99JVTR9YFFYAJOIKWZEQIR9ZJS9S'
          b'JJBWBWWIKRCUS9ZZJYDQPUGKIGHWXCQ9KTKZIXXQLHJKIGJFLJGYGZYSGCLMUVEUHI'
          b'QFKFBDITMAHGOLSSEAUAMSERCDAVHLKWZSBSIYUWNQWL9WNHZOTYINOFISCG9HSCHJ'
          b'JGHPVEETEXHJEVZPK9VMUQTRJXNZSUEBDMWMTPYVHINJWZYSSJDQZDIHAILHNSLWVT'
          b'IOSH9L9BOWTALZHJTQVUEMZJCKCWDKPLBZWIBJBRXFGKRJELVDZOIUAEARPSLQXYCB'
          b'VUOEQTVMBAYYPIAREVYXQNODJWJRLOTSO9QAGZXFSASKMR9RKRJZEEVR9TOBXAMZCG'
          b'VFOAGPOJHWCLTYDPQMDRNRRFETTJEOFBIO9DQEQSYFWFUSUWLUUETHKHNUJMTEZGZO'
          b'BXBMVLDVKVPAT9QCOEODDMDCKBWRJJJQTLETCJDIIBQADDHRYNMF9KFQO9SCMWLUKL'
          b'9WSVOBDDEMEXIDXXCZLHR9DDAVESEQMUUIJHABWAPXSHCOEQOPCRZSTARLMXHCOGJP'
          b'GOMGEIJ9UEJJPHHCODIEGQUDADINVUZW9CPYOD9CZVKRCIKXJLIXYCIRCYTGHTMF9G'
          b'KPEATOTLHHOBVGJHKYFKGEOPVYFZBXPOGLWJVGU9LZFMCEXQGRFAY9UGSPNHMLPCCM'
          b'TFYEOYFZFQSAGBGYZYTYPYROTIQRZOL9GYZWWZH9NYCSILWSPASDHMKHXJTZJESRJU'
          b'SLJJGUSRXNN9SQSJECMPVUVPKLODUMVTYFIISPNFZAVIXKKLPQOWEPPVWOCXA9I9LA'
          b'LPIOCDQKHPPGUABZDLDNUIBHMU9VCUPHKRTVK99IUBHLYCWDZCBMCZMGOWEXLKUQJF'
          b'DX9HWXMOPLNEHOWBDAGZKLYGDLGXYAMT9WNHU9FS9UITGNZPTFGZZVJROGSWHEVCHG'
          b'BDVAZQKPOMZKVZ9YHZGDMILQIGSRRDLQZMRIUYTWQUPNSCHKPLOMIGE9NZFGWJAPZW'
          b'LLOJLXLSLZMYJONJPHIPTCNRE9AXDXKDQTGEVPHQWWCOBTCYLFCCQ9EGVLEARJZMNK'
          b'IIALUYZNYBHNEUKZLNHQVJPAVLWOXLMGBUDMXAMFOHUBOTBDPDCSDBQLYDKATA9OBI'
          b'JNYAPUZEF'
        ),
      ],
    )

    self.assertListEqual(
      ag.get_keys(1),

      [
        SigningKey(
          b'DZRXZABCDULCRMZFVHYJOUB9DSBPVQKGMXTIREWKPYPVRCVIXVILNJTXIOPOXQHDN9'
          b'S9M9TACACAODTITIBNCDYOFKPMZV9WBGMWUHXOLEJDATUSUVPBUZMSBCWRHSVCPUOZ'
          b'KBEWCVFGHSUFPKRSENQQEKXLOKOMA9XZXFZIPPVBTHL9OPCJZSMAOFGERLDITUVIPL'
          b'YFTPZXDFWYRAATUFWWHTLC9MINHQQPGGMBDDFGJOZTSVLN9MANFRICSUKYJWYTACCJ'
          b'IBZC9N9AOX9U9RUNUIKE9PERDFKYGVYCWGKPDMLH9TXVXJUOBXHJZRVOKTYUYUTKVU'
          b'KZJ9TXULXGKTZHJXGVS9YHEUQXC9HSEDIYVOSCZQNBVEFPUJKIZVHRLRIINETNBTBZ'
          b'OYJITWXFTXWPOEDQ9GEMBVI9UTVO9CTTIMTMWSBPNECUYHTUGVSAPLVDEAEWMQW9MC'
          b'LIKNOFQUIIYQWNCZWKNXEKTVT9HSZDTFKXHJHWZBY9N9RY9TTMAIBGHIHQS9AAAUFY'
          b'BRVBMHCVFXPRVFSLBKUIZFKIPDCJQYGHOHQMMBMFIARQYZSZZP9JVAVYVVJCLFNEJJ'
          b'ADDPUVNZIAPCSQIYWHVGCHB9QWICLW9LZVKPMGEFJAICUGWQEPUMOWZHGBIJZ9EJHI'
          b'LMCNLQV9OKEYDGGSJJAGPLFYWQVTHAWHEOQMBALJJCVJS9HLMMIVOSERMDCSKWXNRG'
          b'PZTCGCOUJNWNERTBRMCAEGHREDQDHPV9HWNUJVXNRFDEMU9XHFW9YNJHXAGCZPIEGY'
          b'ZZATBKATSJ9WUVUKPBLQBFROLHXRRRJECEYJBCYVS9LJXBLQTXRFTJOFKSB9IAWBEM'
          b'EPATZKNVSSZLMR9WEKXFQOYKPGNULLMOJLOMLRXPWRWDUGRFIRMWXNQJMJKPMNRHQP'
          b'GTKSWRML9JGPVMAOFNPCIBBIULYMWEGRGEU9GDXEILWNOEPE9BOADDINZCTJBEEICM'
          b'WKBKACYKKLBFEHTNZIEYQVKFIOMUCSFZJYYYSJCOQPXZFKCGOOFQVYTGA9LZY9XKWL'
          b'RTGYUNCREOEOCKNFNWPRCQX9TOXIOWYCIUDXEH9YSSPQB9XRPZZFUHQBSMQRFYQTSO'
          b'Z9PJLWCITLTYAWKXYVJEUATOUB9RJUHTJSRLXBKFFN9DBLGWRJDMOWQVYAOFXWTGPB'
          b'LOFOYILKVBYBGEIFDY9MMMOEVMIFRJGTFARXGUMRQFLETGPEXXGPBHNVIKPWUTVULF'
          b'O9XHGHRO9BBDXFTHGMEGPGFUPEHBXRRJYTCTTJMIHUYPKVGJANAEHFDMNLDJTXJJUS'
          b'IITNDUTQNE9NCSCESCWQQTDEKPVMCRTNAGLYIRSBXBRBSTKDOTXOJFSOPIZJDJAQHV'
          b'UNPUPHJFXRE9VPJUNKMMTLBRJOJHINNWKRJTDEHXEWVFOCUINLOW9FYLMOL9PIXYSE'
          b'RNMERMD9Q9RCX9RGCVOUQWOYKEN9VFQDJXUQAVEGPHUIGFTFUSQPFVQMDAOHEUKWWO'
          b'NXSDPVLQQHTOTFU9HLBKZIGRLQKVNPONQQPATNBVQJJUZFGJOKKNWGX9LNFSVWUNG9'
          b'LPZIQTUCEYXBO99ZCFJIFGTNQMIZ9TYIOBUJAURIFCIDHVNI9BZEOJIQBNVZCZBDTV'
          b'NWJMGPQBFIWRHWVUUGXCHDY9KDTMPEBVLOH9NTTXGZSPMJBXXBSWXTGJWCRDFEKRWP'
          b'VOWYWEMOKUCAIFQXSJHERTZDIHOGAHCBU9VET9VWJXEJHEJSZMBLCFKKRHQVJJLJ9V'
          b'BBSCEYLTNDOIWWCHFG9CWEWAASSDCIKJYCQZMGULSNDEDGQLN9YEXWX9PICDAY9SGH'
          b'EYGTVHZTQCKHHO9RUYWQNPUKZRREAXXTHOOKZAAJFHMERHBTMTGZQBCNTWHGUYQOBT'
          b'AQEOXRFPDDWEVMKEGVY9FSYRLQUCGFQLPVEQ9WHRHNOVIBXPINZEUCRQDDVVESGGWV'
          b'GPTAQBJ9ECJBGAFIPFVVYFDJRUZYMQHOKFNCLFAWFCDQBGRWKLGWH9QXCUSSEECU9Y'
          b'OQJWPRUJNQJEYPGYBZUHQDIOUJHYUFQDFPMMJVABHTWVESLBAEIVGQHSRXPXDKLAKL'
          b'JMPE9WCNWAJKNUVODEALTUHLYWMBMZHHHNYRZHVKJGDEYSKDRKDSFZTLG9ECVNMJCE'
          b'DBPIYONHA'
        ),
      ],
    )

    # You can request a key at any arbitrary index, and the result will
    # always be consistent (assuming the seed doesn't change).
    # Note: this can be a slow process, so we'll keep the numbers small
    # so that tests don't take too long.
    self.assertListEqual(
      ag.get_keys(13),

      [
        SigningKey(
          b'YKEKPCPHHCDVLTSTIZIZ9IEPNLNFOH9KUKWPOWYVOBYJMAZOXMLLIPEGV9EFTGTZIN'
          b'QQNWLKHJFHPPNFG9FVSGHXHNFAEZPGOKDHWSUEJYRHRQBQUT9ZTDOIWLRUDKEQWAVK'
          b'HPGOCUCXMJDXVUHTSBDR9QQSTAOUZVMQAKSCGMZEONTUHHBIYPJLEHVOERXBOUUBBA'
          b'VNMOKNUGVULVWIXOWPSBTGWADVDPXMA99UCYLAOMCIIQLASFDCH9ELGZOBMZQIVXLK'
          b'OTN9CHKIKGYP9MURJDMQBEWDYRYYKZHHEBPFKWSX9CJPVWFMXXVRKRSXKARJHOQWAT'
          b'MDYUZW9HWXFWRFZNNAAZWOJDAU9Z9TFPN9GAVKLKOCYBXRWOQYVXUKQBASZYVWALLQ'
          b'JFUNVDNAERSUIVUBQEIZRKWSFSQNIUBS9CV9BGJVELACHBRXYIIUJPEMK9UYXATOLY'
          b'CPIVPBHFNZRSVFONJCWAQHDTWVRX9OXPGXRIQCOG9ABYHLVYVGBZOAXALIQUDZWDU9'
          b'WOPLLCIJIOSBWVIDHKTXOBMP9PMDPBRNYHGFESMFXVCUTIJICEPFMPQ9OZ9RFSQBDJ'
          b'ZUIDBONHSVYSGGNKNCJNTHWSGLPNKCPJWEEJOSKUEWTWLVXCQPQJOYSGWQPQSRDWBQ'
          b'TZMVXHBYPEKUGQEEAWDIWQGEANMSCCJGBBGJMHC9JPVIA9OXDLYNNSOSMAIAR9KIW9'
          b'OGNPWFHYBOYUXBVUZOTNCLOTTDNXYKWTXCQZZXJAUQMKMKOWH9LODZCTTOBXWSHASL'
          b'ROJUUGJFBBYQEIUVEAWZNHBRVIYJEEMCVFBGUDURGFTGAKTZXZLTNL99MLYPSCHMIT'
          b'WMRRBKTHZBBXXBHTSYL9WTQOWWUENRNIMPPGWJCDVBDAQJQRNLBZBVDLWQHLJYQYHS'
          b'R9OXTMZUURLJWVB9VLSDD9QWUTBLYRNZFIEYECJYSIKBST9ANUXMAFABIOVUOYCCMW'
          b'HABCWLLFTXPLSSGPBIIAVWUQOIKMSDNU9YNGACVDLVSIMFLNJVOODKDCGPLMSBDQVP'
          b'UAGXCJBEVNCTGJBKZWYBBWMBMEFAGPKHGIKVPUVTHSXVA9FUMBTFDZPDSZPJTA9RQF'
          b'GTHGVFSZ9RCKT9XDLPKUILGFAGBY9UXIGSVPMYGLHNXDRVPI9FRKTYVKXXF9ZWHJNO'
          b'JUYPUPLTVPLUMDMGGXMUPD9HHNHORYLOKPCLDZYJCUBNIXDMSLPAIOWCRIETT9PNNB'
          b'VKZDHI9UQQQUFQJTTONTGOLH9RMOVMIAQMUKPUSKEGGBIUXISILL9V99PIGJXJVTSN'
          b'OK9OCSTGDRGF9VFWJRSN9SUTDC9IOPBCMOLUYJIIKWOONQ9IKYQZLGCCFDNOAUMNDY'
          b'DVXDBJNKJYPETMXYUOFWQAICTWSLLCQVGZTPGLVZIWVCDKEYJSKGS9YFVUVMKJWREJ'
          b'IAZPZOHHDBRVUTSJJUNZEOFAASHHXRQRZGAZIVUYDNWSIYKZMUDJWHCJF9DUBULOPS'
          b'NFLRUZVCELFNQSGFXRZVCUGBVBLLFVAERLCTHWUNLFDQFVRSZMFJYWJBDIJP9NBJWB'
          b'DCKGRGTDC9VJGKFFVGNSAIXGONKTBYDBBVKNWOIRW9POJPY9ALBPYESXDDNTWSGRFS'
          b'KTPHMDXH9WHNRDBYWDHVUOFJ9DDMSQDTORHSQYRWOXYWVCTMTPFFEZKGGDTMKSYVOP'
          b'OKRQSUNHQSQ9TVKVXE9HYGVBREVVXAKPUPKES9NKTWBCUAVHUKC9OTWVMERMMIDHDP'
          b'CREDKX9MEJJLCFCUPGUP9JFKDRUF9NAUXPGCCRNA9VBHJBE9FFHFJERFWRUQVAANQM'
          b'ILUEW9DVBPFCKNHXKAMCZLIFQBTQUHJZSVNNJWSJMFDXKXYCPTAEJYQMSUBCYJMBFJ'
          b'KDHVZN9XTCSHXXNAO9PFQAPTJJGPARTJZLJ9NZPVAHEJIGWEZPFHCGJGPOBPGBMZRM'
          b'MUTICVGUMLNCONHOAFTKDHPYZEFCFTDNIMQCBWMRLJPFMFMNUDITECHUCGQXMLKZRL'
          b'VQCQXXKKX9MOMDTPFBI9JQVNRQFRIRIEAYTXDBYWPLYTRHAFYF9LQAVVFOTNUPOTSA'
          b'9TCNZCDVIFQWITACKXQYHBDJURGJFRLVCSNDWAOQNZIN9KBXDIXKROW9BWYZBLSSSC'
          b'LFFUZRVSM'
        ),
      ],
    )
